name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - add-icon

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t tmmanson/tma-backend:latest ./backend/.
        docker push tmmanson/tma-backend:latest

 - name: Trigger webhook
      run: |
        curl -X POST https://hook.itsya0wen.com/hooks/update-tma-backend \
        -H "Content-Type: application/json" \
        -H "x-header-v: ${{ secrets.HEADER_KEY }}" \
        -d '{"action":"push"}'