name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - food-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: Aocker/setup-buildx-action@v2
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t tmmanson/tma-backend:latest ./backend/.
        docker push tmmanson/tma-backend:latest

    - name: Trigger webhook
      run: |
        curl -X POST https://hook.itsya0wen.com/hooks/update-tma-backend \
          -H "Content-Type: application/json" \
          -H "x-header-v: ${{ secrets.HEADER_KEY }}" \
          -d '{"action":"push"}'
